# render.yaml  ── describes all Render services in this repo
services:
  # ── Static site for cart button ─────────────────────────
  - type: web
    name: cart-button-static
    runtime: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: ./frontend/dynamic-checkout-widget
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free

  # ── Optional: Flask web API (commented out to save build time) ─────────
  # - type: web
  #   name: product-search-api
  #   runtime: python
  #   buildCommand: |
  #     pip install -r requirements.txt
  #   startCommand: |
  #     python app.py
  #   envVars:
  #     - key: OPENAI_API_KEY
  #       sync: false
  #     - key: SHOPIFY_DOMAIN
  #       sync: false
  #     - key: SHOPIFY_ADMIN_API
  #       sync: false
  #     - key: EMBEDDINGS_PATH
  #       sync: false
  #     - key: AWS_ACCESS_KEY_ID
  #       sync: false
  #     - key: AWS_SECRET_ACCESS_KEY
  #       sync: false
  #     - key: AWS_DEFAULT_REGION
  #       value: us-east-1
  #   plan: free
